/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication21;

/**
 *
 * @author misbah
 */
import javax.swing.ImageIcon;

public class NewJFrame extends javax.swing.JFrame {
      private int c = 0,i,j,r=0;
      private int b1=0,b2=0,b3=0,b4=0,b5=0,b6=0,b7=0,b8=0,b9=0;
      private int[][] a = new int[3][3];
    

      //ImageIcon z = new ImageIcon("C:\\Users\\misbah\\Documents\\NetBeansProjects\\JavaApplication21\\src\\rsz_new_xero.png");
      ImageIcon z = new ImageIcon("C:\\Users\\misbah\\Documents\\NetBeansProjects\\JavaApplication21\\src\\rsz_blue.png");
      ImageIcon x = new ImageIcon("C:\\Users\\misbah\\Documents\\NetBeansProjects\\JavaApplication21\\src\\rsz_rsz_1419558512_button_cancel.png");

    public NewJFrame() {
        super("misbah.TicTacToe");
        for(i=0;i<=2;i++){
            for(j=0;j<=2;j++){
                a[i][j]=5;
            }
        }
        initComponents();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        again = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setForeground(new java.awt.Color(0, 0, 102));
        setMinimumSize(new java.awt.Dimension(417, 423));
        setPreferredSize(new java.awt.Dimension(417, 423));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));

        again.setBackground(new java.awt.Color(0, 0, 0));
        again.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        again.setForeground(new java.awt.Color(204, 204, 204));
        again.setText("Play Again");
        again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 0, 0));
        exit.setText("Exit Game");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(again, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(again)
                    .addComponent(exit))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setForeground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(0, 0, 51));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton9.setBackground(new java.awt.Color(0, 0, 51));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton6.setBackground(new java.awt.Color(0, 0, 51));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(0, 0, 51));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(0, 0, 51));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton10.setBackground(new java.awt.Color(0, 0, 51));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);

        jButton11.setBackground(new java.awt.Color(0, 0, 51));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.setText("                                 player 1 turn");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(b1==0){  
        if(c==0||c==3||c==6||c==9||c==12){
                jButton3.setIcon(z);
                c=c+1;
                a[0][0]=0;
                if(c!=13){
                jTextField1.setText("                                 player 2 turn");
                }
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton3.setIcon(x);
                c=c+2;
                a[0][0]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
            if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                          r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                         r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                          r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                         r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                }
            }
            if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
            
            }
            b1=1;
       }
       else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
 
           
       
    }                                        

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
       System.exit(0);
    }                                    

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          if(b2==0){
              if(c==0||c==3||c==6||c==9||c==12){
                jButton4.setIcon(z);
                c=c+1;
                a[0][1]=0;
                if(c!=13)
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton4.setIcon(x);
                c=c+2;
                a[0][1]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
           if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                         r=1;
                        jTextField1.setText("                         Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                         r=1;
                        jTextField1.setText("                         Congrats player 2!! You won"); 
                    }
                }
            }
             if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
          
           } 
            b2=1;
          }  
          else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(b5==0){
            if(c==0||c==3||c==6||c==9||c==12){
                jButton6.setIcon(z);
                c=c+1;
                a[1][1]=0;
                if(c!=13)
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton6.setIcon(x);
                c=c+2;
                a[1][1]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
           if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
            }
             if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
          b5=1;
           }
        }
        else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
            
        
    }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(b9==0){
            if(c==0||c==3||c==6||c==9||c==12){
                jButton11.setIcon(z);
                c=c+1;
                a[2][2]=0;
                if(c!=13)  
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton11.setIcon(x);
                c=c+2;
                a[2][2]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
          if(r==0){ 
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                         r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                          r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
            }
           if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }  
          
          b9=1;
          } 
        }
        else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
    }                                         

    private void againActionPerformed(java.awt.event.ActionEvent evt) {                                      
            c=0;
            r=0;
            b1=0;
            b2=0;
            b3=0;
            b4=0;
            b5=0;
            b6=0;
            b7=0;
            b8=0;
            b9=0;
            jButton3.setIcon(null);
            jButton4.setIcon(null);
            jButton5.setIcon(null);
            jButton6.setIcon(null);
            jButton7.setIcon(null);
            jButton8.setIcon(null);
            jButton9.setIcon(null);
            jButton10.setIcon(null);
            jButton11.setIcon(null);
            
            for(i=0;i<=2;i++){
              for(j=0;j<=2;j++){
                a[i][j]=5;
              }
            }
            jTextField1.setText("                                  player 1 turn");
            
    }                                     

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
          if(b8==0){
            if(c==0||c==3||c==6||c==9||c==12){
                jButton10.setIcon(z);
                c=c+1;
                a[2][1]=0;
                if(c!=13)  
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton10.setIcon(x);
                c=c+2;
                a[2][1]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
           if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
            }
           if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
            
           b8=1;
           } 
        }
          else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
    }                                         

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(b6==0){
            if(c==0||c==3||c==6||c==9||c==12){
                jButton7.setIcon(z);
                c=c+1;
                a[1][2]=0;
                if(c!=13)
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton7.setIcon(x);
                c=c+2;
                a[1][2]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
           if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                          r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
            }
           if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
           b6=1;
           } 
        }
        else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(b7==0){
            if(c==0||c==3||c==6||c==9||c==12){
                jButton8.setIcon(z);
                c=c+1;
                a[2][0]=0;
                if(c!=13) 
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton8.setIcon(x);
                c=c+2;
                a[2][0]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
        if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                         r=1; 
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
            }
             if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
      
           b7=1; 
        }   
        }
        else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(b4==0){
           if(c==0||c==3||c==6||c==9||c==12){
                jButton9.setIcon(z);
                c=c+1;
                a[1][0]=0;
                if(c!=13)
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton9.setIcon(x);
                c=c+2;
                a[1][0]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
            if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 2!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
            }
             if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
             b4=1;
            }
           
       }
       else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(b3==0) {
            if(c==0||c==3||c==6||c==9||c==12){
                jButton5.setIcon(z);
                c=c+1;
                a[0][2]=0;
                if(c!=13)
                jTextField1.setText("                                 player 2 turn");
               
            }
            else {
                if(c==1||c==4||c==7||c==10){
                jButton5.setIcon(x);
                c=c+2;
                a[0][2]=1;
                jTextField1.setText("                                 player 1 turn");
                }
            }
           if(r==0){
            if(a[0][0]==0||a[1][1]==0||a[2][2]==0){
                 if(a[0][0]==0){
                     if(a[1][0]==0&&a[2][0]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==0&&a[0][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==0&&a[2][2]==0){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==0){
                    if(a[0][1]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[1][0]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                    if(a[0][2]==0&&a[2][0]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
                if(a[2][2]==0){
                    if(a[0][2]==0&&a[1][2]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                     if(a[2][0]==0&&a[2][1]==0){
                        r=1;
                        jTextField1.setText("                        Congrats player 1!! You won"); 
                    }
                }
            }
            if(a[0][0]==1||a[1][1]==1||a[2][2]==1){
                 if(a[0][0]==1){
                     if(a[1][0]==1&&a[2][0]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                     if(a[0][1]==1&&a[0][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                      if(a[1][1]==1&&a[2][2]==1){
                         r=1;
                         jTextField1.setText("                        Congrats player 1!! You won");
                     }
                         
                 }
                if(a[1][1]==1){
                    if(a[0][1]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[1][0]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                    if(a[0][2]==1&&a[2][0]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
                if(a[2][2]==1){
                    if(a[0][2]==1&&a[1][2]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                     if(a[2][0]==1&&a[2][1]==1){
                        r=1;
                        jTextField1.setText("                        Congrats player 2!! You won"); 
                    }
                }
            }
             if(c==13&&r==0){
                String str="";
                jTextField1.setText(str+"                               Match Drawn!!");
           
            }
        } 
           b3=1;
    }                                        
    else{
             jTextField1.setText("          Wrong Input!! This Tile Is Already Filled!!");
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton again;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
